---
- name: Install Nginx
  apt:
    name: nginx
    install_recommends: no

- name: Create fastcgi_backend File
  template:
    src: fastcgi_backend.j2
    dest: "/etc/nginx/conf.d/fastcgi_backend.conf"
    owner: root
    group: root
    backup: yes

- name: Edit fastcgi_params File
  template:
    src: fastcgi_params.j2
    dest: "/etc/nginx/fastcgi_params"
    owner: root
    group: root
    backup: yes
