---
- name: Copy .bash_aliases File
  template:
    src: bash_aliases.j2
    dest: "/home/magento/.bash_aliases"
    owner: magento
    group: magento
    mode: 0644
    backup: yes

- name: Create Bash Files
  template:
    src: "{{ item | basename }}.j2"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  loop:
    - "server-down"
    - "server-up"
