---
- name: Add Default Nginx Configuration File
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
    backup: yes

- name: Create Symbolic Link
  file:
    src: "/etc/nginx/sites-available/default"
    dest: "/etc/nginx/sites-enabled/default"
    owner: root
    group: root
    state: link

# - name: Restart Nginx Service
#   command: sudo service nginx restart
